spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 9093

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
