spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.hiberate.SQL: debug

server:
  port: 9093

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
