server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java.version: @java.version@
  project: Microservice Dummy
  versionApi: v1
  packageBase: com.kuroshan.workshop.ms.dummy