spring:
  application:
    name: ms-hr-edge-service

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    ms-human-resources-areas:
      service-id: MS-HR-AREAS
      path: /hr/areas/**
      strip-prefix: true
    ms-human-resources-employees:
      service-id: MS-HR-EMPLOYEES
      path: /hr/employees/**
      strip-prefix: true

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'
