spring:
  application:
    name: ms-hr-edge-service
  cloud:
    gateway:
      routes:
        - id: areas
          uri: lb://MS-HR-AREAS
          predicates:
            - Path=/ms-hr-areas/v1/**
        - id: employees
          uri: lb://MS-HR-EMPLOYEES
          predicates:
            - Path=/ms-hr-employees/v1/**

server:
  port: 9090

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 5000
