version: '3.7'
services: 
  microservice-users:
    image: workshopms-microservice-users:v1
    ports: 
      - "8081:8080"
    restart: always
    networks: 
      - workshopms
networks: 
  workshopms:
    external: 
      name: infrastructure_workshopms
